[package]
name = "e06"
version = "0.1.0"
authors = ["Howard Yeh <hayeah@gmail.com>"]
edition = "2018"

[dependencies]
failure = "0.1"
base64 = "0.10.1"
hex = "0.3.2"
hamming = "0.1.3"
cryptopal = { path = "../", version = "0.1.0" }
