[package]
name = "e04"
version = "0.1.0"
authors = ["Howard Yeh <hayeah@gmail.com>"]
edition = "2018"
workspace = ".."

[dependencies]
hex = "0.3.2"
cryptopal = { path = "../", version = "0.1.0" }
failure = "0.1"
failure_derive = "0.1"